# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: false

# Setup
title: GARRY TRINDER
tagline: On a journey in the Microsoft Cloud ...
description: I am driven by finding better ways of solving problems to help people become more productive by sharing my knowledge with others and engaging in discussions, it will inspire us to create innovative solutions to problems using the Microsoft cloud
url: https://garrytrinder.github.io
baseurl: ""
paginate: 5
lang: en_GB

# About/contact
author:
  name: Garry Trinder
  url: https://twitter.com/garrytrinder
  email: garry.trinder@live.com
  twitter: https://twitter.com/garrytrinder
  github: https://github.com/garrytrinder
  linkedin: https://www.linkedin.com/in/gtrinder

# Twitter
twitter:
  username: garrytrinder
  card: summary

# Verification
webmaster_verifications:
  google: 2Ta-fURWtx-kxtVGw_FQT1AbMbsPV7LdDNXlKgTe7Ko

# Custom vars
version: 1.0.0
google_analytics: UA-119232328-1
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
#
